# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $VerbosePreference = 'Continue'
      Write-Verbose 'Downloading Inno Setup 6...'
      Invoke-WebRequest -Uri 'https://jrsoftware.org/download.php/is.exe' -OutFile '$(System.DefaultWorkingDirectory)\is-unicode.exe'
      Write-verbose 'INNO Setup 6 downloaded successfully.'
  

- task: CmdLine@2
  displayName: 'Install INNO Setup 6'
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)/is-unicode.exe /verysilent